### PR TITLE
Make compatible with Python 3

### PR DESCRIPTION
**Pull request by hugovk**
Tested on Python 2.7 and Python 3.9.

### CODE REVIEW

**Review by dangoldin — APPROVED** [review]

**Comment by dangoldin** [comment]
Thanks for the contribution!

**Comment by hugovk** [comment]
You're welcome, thanks for the script!

I ran it on the archives for `@kaikkisanat`, a bot which just finished tweeting every Finnish word for the past 5.5 years. Obviously because it was tweeting on a schedule most of the charts are pretty uniform:

https://twitter.com/hugovk/status/1329471922804035586
https://twitter.com/hugovk/status/1329471927006728194

But this one is interesting, I'm not sure what's going on here, probably it had a hard time because there's too much data?

image

Anyway, no need to fix this, just thought I'd share what's probably a fun glitch!

**Comment by dangoldin** [comment]
Ah interesting. If you want to send me the data I can take a look and debug it. Seems like an interesting puzzle but agree it may be just due to the data given what happens after ~2016-05.

**Comment by hugovk** [comment]
The `tweet.js` file is pretty big, 71 MB!

I added this: 

```diff
     tweets = load_tweets_from_js(options.js_file)

+    from random import randrange
+    keep = []
+    for tweet in tweets:
+        if randrange(1000) == 1:
+            keep.append(tweet)
+    tweets = keep
+    print(len(tweets))
```

And here's the chart for the 99 tweets it selected, which looks much better :)

image

**Comment by dangoldin** [comment]
Nice. I wonder if there's something we can do in the code to deal with the large volumes. I don't tweet that much so didn't really think about the prolific tweeter/bot use case.

**Pull request merged**
